Cinema.UI.Web/Controllers/FilmeController.cs
using Cinema.Aplicacao;
using Cinema.Dominio;
using System.Web.Mvc;

namespace Cinema.UI.Web.Controllers
{
    
    public class FilmeController : Controller
    {
        private readonly FilmeAplicacao appFilme;
        
        public FilmeController()
        {
            appFilme = CinemaAplicacaoConstrutor.FilmeAplicacaoEF();
        }

       
        public ActionResult Index()
        {
            var listaDeFilmes = appFilme.ListarTodos();
            return View(listaDeFilmes);
        }

        public ActionResult Cadastrar()
        {
            return View();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cadastrar(Tbl_FILMES filme)
        {
            if (ModelState.IsValid)
            {
                appFilme.Salvar(filme);
                return RedirectToAction("Index");
            }
            else
                return View(filme);
        }

        public ActionResult Editar(string id)
        {
            var filme = appFilme.ListarPorId(id);

            if (filme == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(filme);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Tbl_FILMES filme)
        {
            if (ModelState.IsValid)
            {
                appFilme.Salvar(filme);
                return RedirectToAction("Index");
            }
            else
                return View(filme);
        }

        public ActionResult Detalhes(string id)
        {
            var filme = appFilme.ListarPorId(id);

            if (filme == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(filme);
            }

        }

        public ActionResult Excluir(string id)
        {
            var filme = appFilme.ListarPorId(id);

            if (filme == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(filme);
            }
        }

        [HttpPost, ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public ActionResult ExcluirConfirmado(string id)
        {
            var filme = appFilme.ListarPorId(id);
            appFilme.Excluir(filme);
            return RedirectToAction("Index");
        }
    }
}

Cinema.UI.Web/Controllers/SessaoController.cs
using Cinema.Aplicacao;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;

namespace Cinema.UI.Web.Controllers
{

    public class SessaoController : Controller
    {
        private readonly SessaoAplicacao appSessao;

        public SessaoController()
        {
            appSessao = CinemaAplicacaoConstrutor.SessaoRepositorioEF();
        }


        public ActionResult Index(string id)
        {
            Session["idFilme"] = id;

            var listaSessao = appSessao.ListarSessao(id);

            return View(listaSessao);
        }

        [HttpGet]
        public IEnumerable Verificar(string data, string hora) {

            string id = Session["idFilme"].ToString();

            //hora 1900 - 01 - 01 11:30:00.000        data 2021 - 06 - 27 00:00:00.000
            DateTime dt = DateTime.ParseExact(data, "d", CultureInfo.CurrentCulture);
            DateTime hr = DateTime.ParseExact(hora, "t", CultureInfo.CurrentCulture);

            var listaSessao = appSessao.ListarSessao(id);

            var dataSessao = listaSessao.FirstOrDefault(x => x.Data == dt && x.Horario.TimeOfDay == hr.TimeOfDay);

            var idSessao = dataSessao.Id_sessao.ToString();

            Session["idSessao"] = idSessao;

            return idSessao;

        }

    
    }
}

Cinema.UI.Web/Views/Filme/Cadastrar.cshtml
@model Cinema.Dominio.Tbl_FILMES

@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastrar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Filme</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Id_classificacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id_classificacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id_classificacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duracao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duracao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duracao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Cinema.UI.Web/Views/Filme/Detalhes.cshtml
@model Cinema.Dominio.Tbl_FILMES

@{
    ViewBag.Title = "Detalhes";
}


<style>
    body {
        background-image: url("../../Assets/movie.jpg");
        background-size: cover;
        background-repeat: no-repeat;
        color: #FFF;
        height: 620px;
    }

    .container {
        display: flex;
        flex-direction: column;
        justify-content: center;
        height: 100%;
        width: 100%;
        padding: 0px;
        background: rgb(10, 10, 10, 0.78);
    }

    .titlePage {
        
        width: 100%;
        text-align: center;
        padding: 20px;
    }

    h1 {
        font-size: 26px;
        font-weight: bold;
        margin: 0;
    }

    .details {
        
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 40px;
    }

    .titleFilme {
        display: flex;
        flex-direction: column;
        text-align: center;
        align-items: center;
    }

        .titleFilme h2 {
            margin: 0;
            font-size: 38px;
            font-weight: 700;
        }

        .titleFilme p {
            font-size: 18px;
            margin: 60px;
            text-align: justify;
            width: 70%;
        }
</style>



<div class="container">

    <div class="titlePage">
        <h1>Detalhes</h1>
    </div>
    <hr style="margin:0" />

    <section class="details">


        <div class="titleFilme">

            <h2>
                @Html.DisplayFor(model => model.Nome)
            </h2>

            <p>
                @Html.DisplayFor(model => model.Descricao)
            </p>

        </div>


        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.Id_classificacao):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Tbl_CLASSIFICACAO.Classificacao)<br>
                @Html.DisplayFor(model => model.Tbl_CLASSIFICACAO.Descricao)<br>
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.Duracao):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Duracao)
            </dd>

        </dl>
    </section>

</div>

<script>

    window.addEventListener('load',
        function () {
            this.document.getElementById("headerId").removeAttribute("hidden", "");
        });

</script>

Cinema.UI.Web/Views/Filme/Editar.cshtml
@model Cinema.Dominio.Tbl_FILMES

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Filme</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Id_classificacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id_classificacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id_classificacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duracao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duracao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duracao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Cinema.UI.Web/Views/Filme/Excluir.cshtml
@model Cinema.Dominio.Tbl_FILMES

@{
    ViewBag.Title = "Excluir";
}

<h2>Excluir</h2>

<h3>Realmente deseja excluir esse registro?</h3>
<div>
    <h4>Filme</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id_classificacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id_classificacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duracao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duracao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> |
            @Html.ActionLink("Cancelar", "Index")
        </div>
    }
</div>

Cinema.UI.Web/Views/Filme/Index.cshtml
@model IEnumerable<Cinema.Dominio.Tbl_FILMES>

@{
    ViewBag.Title = "Lista de Filmes";
}


<style>

    body {
        margin: 0;
        padding: 0
    }

    .titlePage h1 {
        font-weight: bold;
        color: #FFF;
        font-size: 30px;
        margin-bottom: 30px;
    }

    .container {
        width: 100%;
        padding: 0;
        margin: 0;
        background-image: url("../../Assets/movie.jpg");
    }

    .background {
        width: 100%;
        height: 100%;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        text-align: center;
        background: rgb(10 10 10 / 0.78);
    }

    .filmeSection {
        max-width: 940px;
        justify-content: center;
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
        grid-gap: 15px;
        padding: 0px;
    }

    .titleFilme {
        display: flex;
        height: 60px;
        align-items: center;
        justify-content: center;
        padding: 5px;
        background-color: #8B2323;
    }

        .titleFilme p {
            margin: 0;
            padding: 0;
            font-size: 20px;
            font-weight: bold;
            color: #FFF;
        }

    .imgBanner {
        width: 100%;
        height: 380px;
        position: relative;
    }

    .detailFilme {
        width: auto;
        height: 28px;
        font-size: 20px;
        text-align: center;
    }

        .detailFilme a {
            display: flex;
            color: #FFF;
            justify-content: center;
            text-decoration: none;
            background-color: #8B2323;
            transition: 0.2s;
        }

            .detailFilme a:hover {
                background-color: #f31111;
            }

    .btnComprar {
        width: auto;
        height: 28px;
        font-size: 20px;
        text-align: center;
    }

        .btnComprar a {
            display: flex;
            color: #FFF;
            justify-content: center;
            text-decoration: none;
            background-color: #008B00;
            transition: 0.2s;
        }

            .btnComprar a:hover {
                background-color: #38f613;
            }
</style>


<div class="container">

    <div class="background">

        <div class="titlePage">
            <h1>Filmes em cartaz</h1>
        </div>
        <main class="filmeSection">

            @foreach (var item in Model)
            {
                <div class="filmeCard">
                    <!-- <div class="banner"> -->
                    <div class="titleFilme">
                        <p>@Html.DisplayFor(modelItem => item.Nome)</p>
                    </div>
                    <img class="imgBanner" src="https://images.pexels.com/photos/7234241/pexels-photo-7234241.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260"
                         alt="Cartaz do filme">
                    <!-- </div> -->
                    <div class="detailFilme">
                        <a href="#">@Html.ActionLink("Detalhes", "Detalhes", new { id = item.Id })</a>
                    </div>
                    <div class="btnComprar">
                        <a href="#">
                            @Html.ActionLink("Comprar ingresso", "Index", "Sessao", new { id = item.Id }, null)
                        </a>
                    </div>
                </div>
            }

        </main>

    </div>
</div>




<script>
    window.addEventListener('load',
        function () {
            this.document.getElementById("headerId").removeAttribute("hidden", "");
        });
</script>























@*=====================================================================================================*@


@*

    <h2>Filmes</h2>

    <p>
        @Html.ActionLink("Novo Filme", "Cadastrar")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id_classificacao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duracao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Tbl_CLASSIFICACAO.Classificacao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duracao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id=item.Id }) |
                @Html.ActionLink("Detalhes", "Detalhes", new { id=item.Id }) |
                @Html.ActionLink("Excluir", "Excluir", new { id=item.Id })
            </td>
        </tr>
    }

    </table>

*@